### ISSUE TITLE
マスター投票時のプレイヤーの画面

### ISSUE THREAD

**Issue by sasanqua-dev** [prog8-fukurou/frontend#20]
- ws以外

**Comment by haru-036** [comment]
画像を含めた自分の完成形のしおりと、「投票中」の文言

**Comment by sasanqua-dev** [comment]
トップの文言、「どのユーザーに投票しますか」よりも「どのしおりに投票しますか？」の方がいいかもです

**Comment by sasanqua-dev** [comment]
![image](https://github.com/prog8-fukurou/frontend/assets/78304794/bfbeacdd-8016-4138-9b08-d2852fb43be6)

４分割(3つ)を１画面に入れるのは難しそうだったから１画面出して矢印でほかのしおりに移動できるUIの方がいいかもです
